### PR TITLE
Updating the README for improved instruction

### PR DESCRIPTION
**Pull request by h-asmat**

### CODE REVIEW

**Review by peiwangdb — CHANGES_REQUESTED** [review]
@h-asmat thanks for the readme change. Seems you also submitted .DS_store and kanye related files. Could you remove those files from the commit?

**Comment by peiwangdb** [comment]
Thanks for the update @h-asmat ! I noticed there two files included in this commit. Is the .DS_store file relavant?
And the github shows there is a conflict between your code and the master branch, could you resolve it?

**Comment by h-asmat** [comment]
I believe this is resolved now - please let me know!

**Comment by peiwangdb** [comment]
> I believe this is resolved now - please let me know!

I still see the DS.Store file included under the "Files Changed" tab and readme.md has a conflict :(

**Comment by jnwang** [comment]
@dovahcrow, can we get this merged? I want to do some updates on README

**Review by dovahcrow — APPROVED** [review]

**Pull request merged**
